<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3>Konto Arena.pl</h3>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getChildHtml('configchecker'); ?>

<table>
    <tr>
        <td>Subdomena</td>
        <td><?php echo $this->escapeHtml($this->getSubdomain()); ?></td>
    </tr>
    <tr>
        <td>Token</td>
        <td><?php echo $this->escapeHtml($this->getToken()); ?></td>
    </tr>
</table>

<a href="<?php echo Mage::helper('adminhtml')->getUrl('/system_config/edit/section/arenapl'); ?>">zmień</a>

<br>
<br>

<a href="<?php echo Mage::helper('adminhtml')->getUrl('/arenapl/productfullresync'); ?>">całkowita synchronizacja produktów</a>
