<?php /* @var $this ArenaPl_Magento_Block_Categories */ ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3>Kategorie</h3>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getChildHtml('configchecker'); ?>

<?php echo $this->getSaveButtonHtml(); ?>
<table width="100%" id="arenapl-category-mapper">
    <thead>
        <tr>
            <th>Kategoria sklepu</th>
            <th>Kategoria Arena.pl</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->getAllCategories() as $category):
            $currentCategoryEntityId = $category->getEntityId();
            $this->setCategory($category);
            ?>
            <tr data-category-entity-id="<?php echo $currentCategoryEntityId; ?>">
                <td><?php echo $this->displayMagentoCategoryString(); ?></td>
                <td>
                    <?php
                    if ($this->hasMappedTaxon()):
                        $taxonData = $this->getCategoryTaxonData();
                        $baseTaxon = $this->getBaseTaxon($taxonData);
                        $mappedTaxonomyId = $taxonData['taxonomy_id'];
                        $mappedTaxonId = $taxonData['taxon_id'];
                        $mappedBaseTaxonId = $baseTaxon['taxon_id'];
                    else:
                        $taxonData = [];
                        $mappedTaxonomyId = 0;
                        $mappedTaxonId = 0;
                        $mappedBaseTaxonId = 0;
                    endif;
                    ?>
                    <select name="arenapl_main_taxonomies">
                        <option value="0" 
                        <?php
                        if (empty($taxonData)): echo 'selected';
                        endif;
                        ?>>-- wybierz --</option>
                                <?php
                                foreach ($this->getBaseTaxonomies() as $taxon):
                                    ?>
                            <option <?php
                            if ($taxon['taxonomy_id'] == $mappedTaxonomyId && $taxon['taxon_id'] == $mappedBaseTaxonId): echo 'selected';
                            endif;
                            ?> value="<?php echo "$currentCategoryEntityId-{$taxon['taxonomy_id']}-{$taxon['taxon_id']}"; ?>">
                                    <?php
                                    echo $taxon['name'];
                                    ?>
                            </option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                    <div class="arenapl_taxons">
                        <?php
                        if (!empty($taxonData)):
                            ?>
                            <select name="arenapl_taxons[]">
                                <?php
                                foreach ($this->getTaxonomiesSelect($taxonData) as $taxon):
                                    ?>
                                    <option <?php
                                    if ($taxon['taxonomy_id'] == $mappedTaxonomyId && $taxon['taxon_id'] == $mappedTaxonId): echo 'selected';
                                    endif;
                                    ?> value="<?php echo "$currentCategoryEntityId-{$taxon['taxonomy_id']}-{$taxon['taxon_id']}"; ?>">
                                            <?php
                                            echo $taxon['name'];
                                            ?>
                                    </option>
                                    <?php
                                endforeach;
                            endif;
                            ?>
                        </select>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.2/css/select2.min.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.2/js/select2.min.js"></script>
<script type="text/javascript">
    jQuery.noConflict();

    (function ($) {
        var EVENT_SELECT_CHANGED = 'arenapl_select_changed';

        var loadTaxons = function () {
            $this = $(this);
            var selectedOption = $this.val();
            var $taxonsDiv = $this.closest('td').find('div.arenapl_taxons');

            $.getJSON('<?php echo Mage::helper('adminhtml')->getUrl('/arenapl/ajax'); ?>?task=load_taxon_tree&selected_taxonomy=' + selectedOption)
                    .done(function (result) {
                        if (result.status === 'error') {
                            throw new Error(result.message);
                        }

                        $taxonsDiv.empty().append(result.html);
                        $taxonsDiv.find('select[name="arenapl_taxons[]"]').trigger(EVENT_SELECT_CHANGED);
                    })
                    .fail(function (result) {
                        throw new Error('Failed fetching data');
                    });
        };

        $(function () {
            $('#arenapl-category-mapper select').select2();

            $('#arenapl-category-mapper')
                    .on('change', 'select[name="arenapl_main_taxonomies"]', loadTaxons)
                    .on(EVENT_SELECT_CHANGED, function (event) {
                        var $target = $(event.target);
                        $target.select2();
                    });

            window.arenaplSaveCategories = function () {
                var dataToSave = $('#arenapl-category-mapper select[name="arenapl_taxons[]"]').serialize();
                dataToSave += '&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';

                Element.show('loading-mask');

                $.post('<?php echo Mage::helper('adminhtml')->getUrl('/arenapl/savecategorymapping'); ?>?isAjax=true', dataToSave)
                        .done(function (result) {
                            var jsonResult = jQuery.parseJSON(result);
                            if (jsonResult.status === 'error') {
                                throw new Error(jsonResult.message);
                            }
                        })
                        .fail(function (result) {
                            throw new Error('Failed saving data');
                        })
                        .always(function () {
                            Element.hide('loading-mask');
                        });
            };
        });
    }(jQuery));
</script>
<style>
    #arenapl-category-mapper tbody td {
        border-bottom: 1px solid black;
    }
</style>