<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3>Kategorie</h3>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getChildHtml('configchecker'); ?>

<table width="100%">
    <thead>
        <tr>
            <th>Kategoria sklepu</th>
            <th>Kategoria Arena.pl</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->getAllCategories() as $category): ?>
            <tr>
                <td><?php echo $this->displayCategoryString($category); ?></td>
                <td>---</td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>